[2024-11-16T02:51:56.094+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T02:51:56.131+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_sentiment_testing_4.transform_task scheduled__2024-11-15T00:00:00+00:00 [queued]>
[2024-11-16T02:51:56.148+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_sentiment_testing_4.transform_task scheduled__2024-11-15T00:00:00+00:00 [queued]>
[2024-11-16T02:51:56.149+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-16T02:51:56.180+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_task> on 2024-11-15 00:00:00+00:00
[2024-11-16T02:51:56.194+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5511) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-16T02:51:56.197+0000] {standard_task_runner.py:72} INFO - Started process 5514 to run task
[2024-11-16T02:51:56.197+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_sentiment_testing_4', 'transform_task', 'scheduled__2024-11-15T00:00:00+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/ETL_saham_test4.py', '--cfg-path', '/tmp/tmpzsjgndyp']
[2024-11-16T02:51:56.199+0000] {standard_task_runner.py:105} INFO - Job 339: Subtask transform_task
[2024-11-16T02:51:56.293+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_sentiment_testing_4.transform_task scheduled__2024-11-15T00:00:00+00:00 [running]> on host 50375b572a3b
[2024-11-16T02:51:56.439+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_sentiment_testing_4' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-15T00:00:00+00:00'
[2024-11-16T02:51:56.441+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T02:51:56.442+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T02:51:56.443+0000] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-11-16 02:51:56.132258+00:00
[2024-11-16T02:51:56.444+0000] {logging_mixin.py:190} INFO - Dag name:stock_sentiment_testing_4 and current dag run status:running
[2024-11-16T02:51:56.446+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T02:51:56.480+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test4.py", line 131, in transform_task
    final_df, sentiment_agg_df, sentiment_before_merge_df = transform(stock_data, news_data)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test4.py", line 84, in transform
    df_stock = process_stock_data(stock_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test4.py", line 67, in process_stock_data
    df_stock_combined = pd.concat(df_stock_list)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-11-16T02:51:56.512+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-16T02:51:56.513+0000] {logging_mixin.py:190} INFO - Task start:2024-11-16 02:51:56.132258+00:00 end:2024-11-16 02:51:56.511474+00:00 duration:0.379216
[2024-11-16T02:51:56.514+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: stock_sentiment_testing_4> dagrun:<DagRun stock_sentiment_testing_4 @ 2024-11-15 00:00:00+00:00: scheduled__2024-11-15T00:00:00+00:00, state:running, queued_at: 2024-11-16 02:51:35.670287+00:00. externally triggered: False>
[2024-11-16T02:51:56.514+0000] {logging_mixin.py:190} INFO - Failure caused by No objects to concatenate
[2024-11-16T02:51:56.515+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_sentiment_testing_4, task_id=transform_task, run_id=scheduled__2024-11-15T00:00:00+00:00, execution_date=20241115T000000, start_date=20241116T025156, end_date=20241116T025156
[2024-11-16T02:51:56.543+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T02:51:56.544+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 339 for task transform_task (No objects to concatenate; 5514)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test4.py", line 131, in transform_task
    final_df, sentiment_agg_df, sentiment_before_merge_df = transform(stock_data, news_data)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test4.py", line 84, in transform
    df_stock = process_stock_data(stock_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_saham_test4.py", line 67, in process_stock_data
    df_stock_combined = pd.concat(df_stock_list)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-11-16T02:51:56.576+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-16T02:51:56.610+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T02:51:56.612+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
